Repository nationalarchives/ds-wagtail, pull requests merged in 2023-05, with the labels that each got.

#860 UN-589: Wagtail 5.0 upgrade
  etna/records/tests/test_blocks.py
  poetry.lock
  pyproject.toml
Labels: feature, dependencies, python, cross-team

#867 UN-593: Intro image field added to Record Article pages
  etna/articles/migrations/0082_recordarticlepage_intro_image.py
  etna/articles/models.py
  templates/includes/record-revealed.html
Labels: feature, understanding

#868 UN-600: Hide "Discover highlights from the collection" on main
  config/settings/base.py
  templates/articles/article_page.html
Labels: feature, understanding

#887 CHORE: Update dark mode develop theme
  etna/core/wagtail_hooks.py
Labels: chore, cross-team

#905 UN-645: Poetry update
  etna/images/migrations/0008_alter_customimagerendition_file.py
  poetry.lock
  pyproject.toml
Labels: feature, dependencies, python, understanding

#928 UN-661: Featured record article on Topic/Time periods
  templates/collections/topic_explorer_page.html
  templates/includes/related-articles-highlight-cards.html
Labels: feature, understanding

#932 UN-566: Set cG1 on Highlight Gallery
  etna/collections/models.py
Labels: feature, understanding

#898 UN-648: Incorrect home page fields
  etna/core/blocks/__init__.py
  etna/core/blocks/cta.py
  etna/home/blocks.py
  etna/home/migrations/0025_remove_homepage_featured_article_and_more.py
  etna/home/models.py
Labels: feature, understanding

#931 UN-568: Add link + bold/italic features to caption fields
  etna/articles/migrations/0086_alter_articlepage_body.py
  etna/articles/models.py
  etna/core/blocks/image.py
  etna/core/models/mixins.py
  templates/articles/blocks/images/blog-embed__image-container.html
  templates/blocks/image-block-default.html
Labels: feature, understanding

#906 CHORE: Update JS packages
  .platform.app.yaml
  package-lock.json
  package.json
Labels: chore, dependencies, javascript, cross-team

#953 UN-678: Updated Highlight Gallery font colour
  sass/includes/_hero-image.scss
  sass/includes/_highlight-gallery.scss
Labels: fix, understanding

#911 DF-681:Fix record opening year less than four digits
  etna/search/templatetags/search_tags.py
  etna/search/tests/test_search_tags.py
Labels: fix, finding

#960 CHORE: JS package updates
  package-lock.json
  package.json
  sass/includes/search/_search-results__list-card.scss
Labels: chore, dependencies, javascript, cross-team
