Repository nationalarchives/ds-wagtail, pull requests merged in 2023-06, with the labels that each got.

#957 UN-677: Article title label
  etna/articles/models.py
  sass/includes/_card-groups.scss
  sass/includes/related-article-cards.scss
  templates/articles/article_index_page.html
  templates/home/home_page.html
  templates/includes/article-spotlight.html
  templates/includes/card-group-secondary-nav.html
  templates/includes/related-article-cards.html
Labels: feature, understanding

#959 UN-676: Record Article new label
  etna/articles/migrations/0087_recordarticlepage_mark_new_on_next_publish_and_more.py
  etna/articles/migrations/0088_alter_recordarticlepage_mark_new_on_next_publish.py
  etna/articles/models.py
Labels: feature, understanding

#958 UN-673: Article and Record Article page chooser
  etna/articles/migrations/0089_alter_articleindexpage_featured_article.py
  etna/articles/models.py
  templates/articles/article_index_page.html
Labels: feature, understanding

#933 CHORE: Make text-indent only on mobile view
  sass/includes/_header.scss
Labels: chore, cross-team

#879 DF-658: Back to search results
  etna/records/tests/test_views.py
  etna/records/views/records.py
  etna/search/tests/test_views.py
  etna/search/views.py
  templates/includes/records/record-cta-panel.html
Labels: feature, understanding, finding

#998 UN-699: Topic and Time period intro colour
  sass/includes/_highlight-intro.scss
Labels: fix, understanding

#995 UN-703: Topic and Time period pages stories cards analytics
  sass/etna.scss
  sass/includes/related-article-cards.scss
  templates/collections/time_period_explorer_page.html
  templates/collections/topic_explorer_page.html
  templates/includes/related-article-cards.html
Labels: feature, understanding

#988 UN-688: THE STORY OF and RECORD REVEALED styling
  sass/includes/_card-groups.scss
  templates/articles/article_index_page.html
Labels: feature, understanding

#1007 UN-651: FIX Featured record article tracking
  templates/includes/record-revealed.html
Labels: fix, understanding

#1020 DF-688:Update contry filter label
  etna/search/forms.py
Labels: finding

#1027 CHORE: Update JS packages
  package-lock.json
  package.json
Labels: chore, dependencies, javascript, cross-team

#1033 UN-724: Added link to record reference in Highlight Gallery
  templates/includes/highlights-gallery.html
Labels: feature, understanding

#970 UN-587: Focused article page
  etna/articles/migrations/0091_focusedarticlepage.py
  etna/articles/models.py
  etna/collections/models.py
  etna/core/models/mixins.py
  templates/articles/focused_article_page.html
Labels: feature, understanding

#996 UN-702 + 704: Publication date field updates
  etna/articles/blocks.py
  etna/articles/migrations/0092_alter_articlepage_body_alter_focusedarticlepage_body.py
  etna/core/blocks/promoted_links.py
  templates/articles/blocks/featured_link.html
  templates/articles/blocks/promoted_pages.html
Labels: feature, understanding

#992 UN-700: Add datalayer to the BE of all required pages
  etna/articles/models.py
  etna/collections/models.py
Labels: understanding

#1039 DF-708:Discovery links for record details
  etna/ciim/constants.py
  etna/records/models.py
  etna/records/templatetags/records_tags.py
  etna/records/tests/test_templatetags.py
  etna/records/views/records.py
  templates/includes/records/record-crosslink-panel.html
Labels: finding

#1034 UN-719: Link list analytics
  templates/articles/blocks/promoted_list_block.html
Labels: understanding

#1028 UN-715: Stories button CE index page analytics
  templates/collections/explorer_index_page.html
Labels: understanding

#1070 UN-729: Publication date help text
  etna/articles/blocks.py
  etna/articles/migrations/0093_alter_articlepage_body_alter_focusedarticlepage_body.py
  etna/core/blocks/promoted_links.py
Labels: understanding

#1071 UN-736: CE soft launch prep
  etna/articles/blocks.py
  etna/articles/migrations/0094_alter_articleindexpage_featured_pages.py
  etna/articles/models.py
  etna/collections/models.py
  templates/articles/blocks/featured_collection.html
Labels: understanding

#1072 Release 7.0.0 into main
  etna/articles/blocks.py
  etna/articles/migrations/0093_alter_articlepage_body_alter_focusedarticlepage_body.py
  etna/articles/migrations/0094_alter_articleindexpage_featured_pages.py
  etna/articles/models.py
  etna/collections/models.py
  etna/core/blocks/promoted_links.py
  etna/search/views.py
  sass/includes/_promoted-pages.scss
  sass/includes/_transcription.scss
  templates/articles/blocks/featured_collection.html
  templates/articles/blocks/promoted_pages.html
  templates/articles/record_article_page.html
  templates/collections/explorer_index_page.html
  templates/includes/card-group-secondary-nav.html
  templates/search/blocks/search_filters.html
Labels: release

#863 CHORE: Update documentation for deployments and other topics
  README.md
  docs/developer-guide/contributing.md
  docs/developer-guide/dependency-management.md
  docs/developer-guide/fetching-data.md
  docs/developer-guide/frontend.md
  docs/developer-guide/project-conventions.md
  docs/developer-guide/vscode.md
  docs/infra/configuring-an-environment.md
  docs/infra/environments.md
  mkdocs.yml
Labels: chore

#1106 CHORE: JS package updates
  package-lock.json
  package.json
Labels: dependencies, javascript

#1105 UN-762: Poetry update
  poetry.lock
  pyproject.toml
Labels: dependencies, python

#1130 UN-783: Remove publication date from Focused Article
  templates/articles/focused_article_page.html
Labels: understanding
